name: PureChat
main: _64FF00\PureChat\PureChat
version: "1.5.0"
api: [1.13.0, 2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
load: POSTWORLD
author: 64FF00 and NekoGirl
website: https://github.com/PurePlugins/PureChat
depend: [PurePerms]
softdepend: [FactionsPro, XeviousPE-Factions]
commands:
  listformat: 
      description: "Lists all formmating varables! WIP"
      permission: pchat.command.listformat
  setformat:
      description: "Allows you to set default chat format of a PurePerms group"
      permission: pchat.command.setformat
  setnametag:
    description: "Allows you to set default nametag of a PurePerms group"
    permission: pchat.command.setnametag
  setprefix:
    description: "Allows you to set your PureChat prefix"
    permission: pchat.command.setprefix
  setsuffix:
    description: "Allows you to set your PureChat suffix"
    permission: pchat.command.setsuffix	
permissions:
  pchat:
    description: "PureChat by 64FF00! (Twitter: @64FF00) Modified by NekoGirl678!"
    children:
      pchat.command:
        description: "Allows you to use all PureChat commands."
        children:
          pchat.command.listformat:
            description: "Allows you to view formatting varables"
          pchat.command.setformat:
            description: "Allows you to set default chat format of a PurePerms group"
          pchat.command.setnametag:
            description: "Allows you to set default nametag of a PurePerms group"
          pchat.command.setprefix:		
            description: "Allows you to set your PureChat prefix"
          pchat.command.setsuffix:		
            description: "Allows you to set your PureChat suffix"			
      pchat.coloredMessages:
        description: "Allows you to use colors in chat"		
